#!/bin/bash

#Ring Chest

if ! grep -Po <<< Ring $Inv &> /dev/null; then
        printf "\n"
        echo "You find a shiny ring that easily fits onto your ring finger. "
        printf "\n"
        echo "As you try on this Ring, you feel a strange sensation surround your body."
        printf "\n"
	echo "You inspect the ring and find a small eagle flapping its wings at its base. You then infer that this ring has given you an increase in your agility as you happen walk at speeds unaccustomed to you. "
	printf "\n"
        echo "Remember to equip the Ring! Use the following command to do so:"
        printf "\n"
        echo "export Inv=Ring,\$Inv"
        printf "\n"
        echo "By using export, we create an environmental variable."
        printf "\n"
        echo "Check your inventory at any time by typing in echo \$Inv"
        printf "\n"
	mv ./.button ./button 2>/dev/null
else
        echo "There is nothing in the chest!"
fi
