#!/bin/bash
#shield Code

if ! grep -Po <<< Shield $Inv &> /dev/null; then

	printf "\n"
	echo "In the distance you see a shield on a skeleton body."

	printf "\n"
	echo "You move closer to see what the object on the body was and you find out it is a shield made from dragon scales."
	printf "\n"

	echo "Remember to store the shield in your inventory! Use the following command to do so:"
	printf "\n"

	echo "export Inv=Shield,$Inv"
	printf "\n"

	echo "By using export, we create an environmental variable."
	printf "\n"

	echo "Check your inventory at any time by typing in echo \$Inv"
	printf "\n"
	mv ./.youngDragon ./youngDragon 2>/dev/null
else
        echo "You already have a shield!"
fi
