#!/bin/bash

echo "As you pick up the sword, the snake's eyes begin to resonate with a button on the wall, both glowing red."
echo
read -p "Will you go press the button? Y/N: " ANSWER

case "$ANSWER" in
	[Yy] )	
		echo "The walls split and slowly slide apart, revealing a pathway!"
		mv ../.pathway ./pathway 2>/dev/null
		echo
		echo "Remember that you can traverse using cd."
		echo
		echo "There is a shortcut you can use to autocomplete this!"
		echo
		echo "By pressing TAB, you can autocomplete most commands and filenames, as long as they are valid."
		echo
		echo "Type in cd path and press TAB to autocomplete the directory name"
		;;
	[Nn])
		echo "You decide not to press the button."
		;;
esac
