#!/bin/bash
#treasure chest code

if ! grep -Po <<< Sword $Inv &> /dev/null
then
        echo
        echo "You find a sword with what looks to be a snake wrapped around the hilt."
        echo
        echo "As you pick up the sword, the snake hisses at you for a second before calming down."
        echo
        echo "Remember to store this sword in your inventory! Use the following command to do so:"
        echo
        echo "export Inv=Sword,\$Inv"
        echo
        echo "By using export, we create an environmental variable."
        echo
        echo "Check your inventory at any time by typing in echo \$Inv"
        echo 
	mv ./.serpent ./serpent 2>/dev/null
else
        echo "You already have a sword!"
fi
